// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"cz/app/interface/main/internal/conf"
	"cz/app/interface/main/internal/server/http"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	ginHandler := http.NewGinHandler(bootstrap, logger)
	server := http.NewHTTPServer(bootstrap, ginHandler, logger)
	app := newApp(logger, server, bootstrap)
	return app, func() {
	}, nil
}
