// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollectionClient is the client API for Collection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionClient interface {
	// Sends a greeting
	GetCollectionList(ctx context.Context, in *GetCollectionListReq, opts ...grpc.CallOption) (*GetCollectionListRes, error)
	GetCollection(ctx context.Context, in *GetCollectionReq, opts ...grpc.CallOption) (*GetCollectionRes, error)
	DoCollect(ctx context.Context, in *DoCollectReq, opts ...grpc.CallOption) (*DoCollectRes, error)
	UndoCollect(ctx context.Context, in *UndoCollectReq, opts ...grpc.CallOption) (*UndoCollectRes, error)
	IsCollected(ctx context.Context, in *IsCollectedReq, opts ...grpc.CallOption) (*IsCollectedRes, error)
}

type collectionClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionClient(cc grpc.ClientConnInterface) CollectionClient {
	return &collectionClient{cc}
}

func (c *collectionClient) GetCollectionList(ctx context.Context, in *GetCollectionListReq, opts ...grpc.CallOption) (*GetCollectionListRes, error) {
	out := new(GetCollectionListRes)
	err := c.cc.Invoke(ctx, "/cz_collection_v1.Collection/GetCollectionList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClient) GetCollection(ctx context.Context, in *GetCollectionReq, opts ...grpc.CallOption) (*GetCollectionRes, error) {
	out := new(GetCollectionRes)
	err := c.cc.Invoke(ctx, "/cz_collection_v1.Collection/GetCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClient) DoCollect(ctx context.Context, in *DoCollectReq, opts ...grpc.CallOption) (*DoCollectRes, error) {
	out := new(DoCollectRes)
	err := c.cc.Invoke(ctx, "/cz_collection_v1.Collection/DoCollect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClient) UndoCollect(ctx context.Context, in *UndoCollectReq, opts ...grpc.CallOption) (*UndoCollectRes, error) {
	out := new(UndoCollectRes)
	err := c.cc.Invoke(ctx, "/cz_collection_v1.Collection/undoCollect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionClient) IsCollected(ctx context.Context, in *IsCollectedReq, opts ...grpc.CallOption) (*IsCollectedRes, error) {
	out := new(IsCollectedRes)
	err := c.cc.Invoke(ctx, "/cz_collection_v1.Collection/isCollected", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionServer is the server API for Collection service.
// All implementations must embed UnimplementedCollectionServer
// for forward compatibility
type CollectionServer interface {
	// Sends a greeting
	GetCollectionList(context.Context, *GetCollectionListReq) (*GetCollectionListRes, error)
	GetCollection(context.Context, *GetCollectionReq) (*GetCollectionRes, error)
	DoCollect(context.Context, *DoCollectReq) (*DoCollectRes, error)
	UndoCollect(context.Context, *UndoCollectReq) (*UndoCollectRes, error)
	IsCollected(context.Context, *IsCollectedReq) (*IsCollectedRes, error)
	mustEmbedUnimplementedCollectionServer()
}

// UnimplementedCollectionServer must be embedded to have forward compatible implementations.
type UnimplementedCollectionServer struct {
}

func (UnimplementedCollectionServer) GetCollectionList(context.Context, *GetCollectionListReq) (*GetCollectionListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionList not implemented")
}
func (UnimplementedCollectionServer) GetCollection(context.Context, *GetCollectionReq) (*GetCollectionRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollection not implemented")
}
func (UnimplementedCollectionServer) DoCollect(context.Context, *DoCollectReq) (*DoCollectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoCollect not implemented")
}
func (UnimplementedCollectionServer) UndoCollect(context.Context, *UndoCollectReq) (*UndoCollectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndoCollect not implemented")
}
func (UnimplementedCollectionServer) IsCollected(context.Context, *IsCollectedReq) (*IsCollectedRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsCollected not implemented")
}
func (UnimplementedCollectionServer) mustEmbedUnimplementedCollectionServer() {}

// UnsafeCollectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionServer will
// result in compilation errors.
type UnsafeCollectionServer interface {
	mustEmbedUnimplementedCollectionServer()
}

func RegisterCollectionServer(s grpc.ServiceRegistrar, srv CollectionServer) {
	s.RegisterService(&Collection_ServiceDesc, srv)
}

func _Collection_GetCollectionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServer).GetCollectionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cz_collection_v1.Collection/GetCollectionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServer).GetCollectionList(ctx, req.(*GetCollectionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collection_GetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServer).GetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cz_collection_v1.Collection/GetCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServer).GetCollection(ctx, req.(*GetCollectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collection_DoCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoCollectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServer).DoCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cz_collection_v1.Collection/DoCollect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServer).DoCollect(ctx, req.(*DoCollectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collection_UndoCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoCollectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServer).UndoCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cz_collection_v1.Collection/undoCollect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServer).UndoCollect(ctx, req.(*UndoCollectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collection_IsCollected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsCollectedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServer).IsCollected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cz_collection_v1.Collection/isCollected",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServer).IsCollected(ctx, req.(*IsCollectedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Collection_ServiceDesc is the grpc.ServiceDesc for Collection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Collection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cz_collection_v1.Collection",
	HandlerType: (*CollectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCollectionList",
			Handler:    _Collection_GetCollectionList_Handler,
		},
		{
			MethodName: "GetCollection",
			Handler:    _Collection_GetCollection_Handler,
		},
		{
			MethodName: "DoCollect",
			Handler:    _Collection_DoCollect_Handler,
		},
		{
			MethodName: "undoCollect",
			Handler:    _Collection_UndoCollect_Handler,
		},
		{
			MethodName: "isCollected",
			Handler:    _Collection_IsCollected_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collection.proto",
}
