name: cz-api
version: 0.1.0
logger:
  fluent_addr: tcp://localhost:24224
  file: _
  stdout: true
  enable_fluent: false
  enable_file: false
server:
  http:
    addr: 0.0.0.0:6001
    timeout: 9000000000000000000
client:
  collection_client:
    name: cz-collection
cz:
  base: http://localhost:8000
registry:
  enable: false
  consul:
    address: "106.15.186.195:8500"
    schema: "http"

