name: cz-collection
version: 0.1.0
logger:
  fluent_addr: tcp://fluentd:24224
  file: _
  stdout: true
  enable_fluent: false
  enable_file: false
server:
  http:
    addr: 0.0.0.0:8010
    timeout: 1000000000000000000
  grpc:
    addr: 0.0.0.0:9000
    timeout: 9000000000000000000  # nano
data:
  mysql:
    user: xd
    password: xd#123456
    host: 47.98.146.46
    port: "33061"
    database: xd_test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 2000
    write_timeout: 2000
registry:
  name: cz-collection
  enable: false
  consul:
    address: "localhost:8500"
    schema: "http"

